name: .NET Core Desktop

on:
  workflow_dispatch:
  push:
    branches:
       - master
    paths-ignore: 
       - ".github/**"
       - "README.md"

jobs:

  build:

    runs-on: windows-latest
    steps:
         - name: Checkout
           uses: actions/checkout@v3
           with:
              fetch-depth: 0
              ref: master

    # Install the .NET Core workload
         - name: Install .NET Core
           uses: actions/setup-dotnet@v3
           with:
              dotnet-version: 6.0.x

    # Restore the application to populate the obj folder with RuntimeIdentifiers
         - run: |
               dotnet build TurtleComandApp.sln --configuration release


    # Decode the base 64 encoded pfx and save the Signing_Certificate
         - name: Decode the pfx
           run: |
                $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
                 $certificatePath = Join-Path -Path ${{github.Workspace}} -ChildPath GitHubActionsWorkflow.pfx
                 [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
           shell: pwsh


         - name: Create the app package
           run: msbuild ${{env.Project}} /p:Configuration=${{env.Configuration}} /p:UapAppxPackageBuildMode=${{env.Appx_Package_Build_Mode}} /p:AppxBundle=${{env.Appx_Bundle}} /p:PackageCertificateKeyFile=GitHubActionsWorkflow.pfx /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
           env:
               Appx_Bundle: Always
               Appx_Bundle_Platforms: x86|x64
               Appx_Package_Build_Mode: StoreUpload
               Configuration: "release"
               Project: "TurtleComandApp.csproj"

    # Remove the pfx
         - name: Remove the pfx
           run: Remove-Item -path ${{github.Workspace}}\GitHubActionsWorkflow.pfx

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
         - name: Upload build artifacts
           uses: actions/upload-artifact@v3
           with:
                name: MSIX Package
                path: ${{ github.workspace }}\AppPackages
