name: Generate EXE
run-name: Build Release-${{ github.run_number }} 
on:
  workflow_dispatch:
  push:
    branches:
       - master
    paths-ignore: 
       - ".github/**"
       - "README.md"
       - "setup/**"

jobs:

  build:

    runs-on: windows-latest
    permissions: 
       contents: write
    env:
      RELEASE: "v${{github.run_number}}"
    steps:
         - name: Checkout
           uses: actions/checkout@v3
           with:
              fetch-depth: 0
              ref: master

    # Install the .NET Core workload
         - name: Install .NET Core
           uses: actions/setup-dotnet@v3
           with:
              dotnet-version: 8.0.x

    # Restore the application to populate the obj folder with RuntimeIdentifiers
         - run: |
               dotnet build TurtleCommandApp.sln --configuration release --output "${{github.workspace}}\setup"

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
         - name: Upload build artifacts
           uses: actions/upload-artifact@v3
           with:
                name: Setup Exe
                path: ${{ github.workspace }}\setup

         - name: Upload the Build
           run:  |
              git add setup
              git commit -m "setup has been updted."
              git push origin
                 


        
                
