name: Release Exe
run-name: Setup Release-${{ github.run_number }} 
on:
  workflow_call:
    inputs:
         release_version:
          type: string
          required: true
          description: "Release version number"

jobs:
 create-release:
       runs-on: windows-latest
       permissions: 
         contents: write
       env:
         RELEASE: "v${{inputs.release_version}}"
       steps: 

        - name: Create Tag
          run: |
           git tag  ${{env.RELEASE}}
           git push origin  ${{env.RELEASE}}


        - name: Release
          uses: softprops/action-gh-release@v1
          with:
             name: Release - ${{env.RELEASE}}
             tag_name: ${{env.RELEASE}}
             generate_release_notes: true
             draft: false
             prerelease: false
             files: ""